### DISCUSSION TITLE
Aligning Geist UI Tab label to center

### DISCUSSION THREAD

**Discussion by thecamp-discord** [zeit-ui/react#629] [Q&A]
Hey, I just want to ask on how to align the label of `Tab` Component to the center. I'm currently exploring and studying react
or CSS. Is it possible within CSS style? if so, answers are highly appreciated

**Comment by harshcut** [comment]
Try applying `flex` properties to class `tabs`.

```css
:global(.tabs) {
  display: flex;
  align-items: center;
  justify-content: center;
}
```

![image](https://user-images.githubusercontent.com/86551248/132937342-2695c284-f41d-4302-890b-d44127013c73.png)
