### DISCUSSION TITLE
Is there a numeric input?

### DISCUSSION THREAD

**Discussion by recursivevoidptr** [zeit-ui/react#644] [Q&A]
So I want to know if there is an input that accepts numbers only?

**Comment by Deep-Codes** [comment]
You can do it this way

```jsx
<Input htmlType ='number'  placeholder="Geist UI" />
```

<img width="832" alt="Screenshot 2021-10-18 at 5 49 13 PM" src="https://user-images.githubusercontent.com/61158210/137728977-e7336fa0-64c2-4a79-8f70-d290e32209ff.png">

**Reply by recursivevoidptr** [reply]
How to hide the button there?

**Reply by Deep-Codes** [reply]
Adding some CSS styles should solve it

```css
input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
  -webkit-appearance: none;
  margin: 0;
}

input[type=number] {
  -moz-appearance: textfield;
}
```

Here's an example

<img width="814" alt="Screenshot 2021-10-19 at 9 09 13 AM" src="https://user-images.githubusercontent.com/61158210/137839968-8f6a58e4-8e54-45b6-b6e2-74cc1b55eb32.png">
